### ISSUE TITLE
External URL links not working

### ISSUE THREAD

**Issue by adalbertopc** [pokedotdev/twitter-clone#1]
Profile Bio website not working when URL doesnt have `https://www.`

<img width="276" alt="image" src="https://user-images.githubusercontent.com/58749813/184295995-780cd3df-fb20-4775-89bc-9fb324b602fc.png">

<img width="428" alt="image" src="https://user-images.githubusercontent.com/58749813/184296067-e627cb5c-e1de-460c-b30d-4baeb4db6fd5.png">

**Comment by pokedotdev** [comment]
I was aware of this, but had forgotten about it.

The issue is fixed, thank you very much!
